<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-451F43I" name="TestValidationText" tests="1" failures="1" timestamp="6 Mar 2018 04:45:34 GMT" time="11.572" errors="0">
  <testcase name="textValidation" time="0.135" classname="Academy.validatetext">
    <failure type="java.lang.AssertionError" message="expected [CHECK IT OUT] but found []">
      <![CDATA[java.lang.AssertionError: expected [CHECK IT OUT] but found []
	at Academy.validatetext.textValidation(validatetext.java:31)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- textValidation -->
</testsuite> <!-- TestValidationText -->
